substitutions:
  name: louder1
  friendly_name: My New Esparagus Louder
  destination_player: media_player.match_name

packages:
  louder: !include
    file: "packages/esparagus-louder.yml"
    vars:
      log_level: INFO
      enable_display: true
  remote: !include
    file: "./example-esparagus-remote.yml"
    vars:
      gpio_pin: 39
      led_id: rgb_front_led

# Enable Home Assistant API
api:
  encryption:
    key: "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE="

ota:
  - platform: esphome
    password: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

wifi:
  ssid: example
