substitutions:
  name: loud1
  friendly_name: My New Esparagus Loud
  destination_player: media_player.ha_name

packages:
  loud: !include
    file: "packages/esparagus-loud.yml"
    vars:
      enable_display: true
  # This would need adjusting to your own remote codes
  remote: !include
    file: "./example-esparagus-remote.yml"
    vars:
      gpio_pin: 39
      led_id: rgb_front_led

# Enable Home Assistant API
api:
  encryption:
    key: "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE="

ota:
  - platform: esphome
    password: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

wifi:
  ssid: example
