defaults:
  task_stack_in_psram: false
  log_level: INFO
  enable_ethernet: false
  enable_display: false
  enable_debug: false
  channel_mode: stereo

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: Esparagus Louder
  project:
    name: "sonocotta.esparagus_louder"
    version: "revG"
  min_version: 2026.2.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  # Important! Play sound on boot required for DAC to capture clock signal and enable DSP configuration
  # If any of the DSP configs are sent before clock signal, they are simply ignored. This applies to EQ and Mixer controls
  on_boot:
    priority: 220.0
    then:
      media_player.play_media:
        id: external_media_player
        media_url: file://startup_sync_sound

substitutions:
  pkg_ethernet: !include
    file: "./esparagus-louder-ethernet.yml"
  pkg_display: !include
    file: "./esparagus-display.yml"
    vars:
      display_cs: GPIO15
      display_dc: GPIO04
      display_reset: GPIO32
      speaker_id: external_media_player

  pkg_debug: !include
    file: "./debug.yml"

packages:
  base: !include
    file: "./esparagus.yml"
    vars:
      led_gpio_pin: 12
  remote: !include
    file: "./esparagus-remote.yml"
    vars:
      gpio_pin: 39
      led_id: rgb_front_led
  display: ${ pkg_display if enable_display else {} }
  debug: ${ pkg_debug if enable_debug else {} }
  ethernet: ${ pkg_ethernet if enable_ethernet else {} }

external_components:
  - source: github://mrtoy-me/esphome-tas5805m@beta
    components: [ tas5805m ]
    refresh: 1h

esp32:
  board: mhetesp32minikit
  flash_size: 16MB # louder has more flash

network:
  enable_ipv6: true

globals:
  - id: current_volume
    type: float
    initial_value: '0.2'
  - id: announcement_triggered
    type: bool
    initial_value: 'false'
    
media_source:
  # Additional file for booting the DAC
  - platform: file
    id: file_source
    files:
      id: startup_sync_sound
      file: https://github.com/mrtoy-me/esphome-tas5805m/raw/main/components/tas5805m/tas5805m_boot_louder.flac
i2c:
  sda: GPIO21
  scl: GPIO27
  frequency: 400kHz
  timeout: 100us
  scan: True

### TAS5805M DAC configuration
audio_dac:
  - platform: tas5805m
    id: tas5805m_dac
    enable_pin: GPIO33  # Physical pin connected to PWDN pin
    dac_mode: BTL       # 'BTL' / Bridge Tied Load - 2Ch Stereo, or 'PBTL' / Parallel Bridge Tied Load - 1Ch Mono (double power)
    mixer_mode: STEREO  # STEREO, STEREO_INVERSE, MONO, LEFT, RIGHT
    analog_gain: -6db   # Startup Gain or Output voltage swing - pick based on the power supply voltage: https://github.com/sonocotta/esp32-tas5805m-dac?tab=readme-ov-file#digital-volume-and-analog-gain
    # volume_max: -6dB  # Max HA volume mapping to Digital Volume control, goes as high as +24dB, but not recommend going much above 0 dB, risking to cause clipping on high volume
    volume_min: -60db   # Min HA volume mapping to Digital Volume control, goes as low as -103dB, but prefer to set higher to have a reasonable volume range
    update_interval: 5s # How often fault registers are read and cleared

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: i2s_speaker_id
    sample_rate: 48000
    i2s_dout_pin: GPIO22
    # TODO check if this can this be lowered
    bits_per_sample: 32bit
    dac_type: external
    channel: ${channel_mode}
    timeout: never
    mclk_multiple: 512
    use_apll: true
    buffer_duration: 200ms
    audio_dac: tas5805m_dac

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: i2s_speaker_id
    num_channels: 2
    task_stack_in_psram: ${task_stack_in_psram}
    source_speakers:
      - id: announcement_mixer_input
        timeout: never
      - id: media_mixer_input
        timeout: never

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

  - platform: speaker_source
    id: external_media_player
    volume_increment: 2%
    volume_initial: 25%
    name: Media Player
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    announcement_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1  # Stereo audio is unnecessary for announcements
      sample_rate: 48000
    media_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 2
      sample_rate: 48000
    sources:
      - file_source
      - http_source
      - sendspin_source
    on_announcement:
      - if:
          condition:
            - lambda: return (!id(announcement_triggered));
          then:
            - lambda: |-
                id(announcement_triggered) = true;
                id(current_volume) = id(external_media_player).volume;
            - mixer_speaker.apply_ducking:
                  id: media_mixer_input
                  decibel_reduction: 40
                  duration: 0.0s
            - wait_until:
                media_player.is_announcing: external_media_player
            - delay: 0.75s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(announce_volume).state / 100.0;"
            - wait_until:
                - not:
                    media_player.is_announcing: external_media_player
            - mixer_speaker.apply_ducking:
                      id: media_mixer_input
                      decibel_reduction: 0
                      duration: 1.0s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(current_volume);"
            - lambda: id(announcement_triggered) = false;
      
    on_state:
      if:
        condition:
          and:
            - lambda: return (!id(announcement_triggered));
            - not:
                media_player.is_announcing: external_media_player
        then:
          - mixer_speaker.apply_ducking:
              id: media_mixer_input
              decibel_reduction: 0
              duration: 1.0s

number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50
    optimistic: true

  - platform: tas5805m
    eq_gain_band20Hz:
      name: Gain ---20Hz
    eq_gain_band31.5Hz:
      name: Gain ---31.5Hz
    eq_gain_band50Hz:
      name: Gain ---50Hz
    eq_gain_band80Hz:
      name: Gain ---80Hz
    eq_gain_band125Hz:
      name: Gain --125Hz
    eq_gain_band200Hz:
      name: Gain --200Hz
    eq_gain_band315Hz:
      name: Gain --315Hz
    eq_gain_band500Hz:
      name: Gain --500Hz
    eq_gain_band800Hz:
      name: Gain --800Hz
    eq_gain_band1250Hz:
      name: Gain -1250Hz
    eq_gain_band2000Hz:
      name: Gain -2000Hz
    eq_gain_band3150Hz:
      name: Gain -3150Hz
    eq_gain_band5000Hz:
      name: Gain -5000Hz
    eq_gain_band8000Hz:
      name: Gain -8000Hz
    eq_gain_band16000Hz:
      name: Gain 16000Hz

switch:
  # Enable USB-PD trigger chip. Will request 19V from the power supply, but might be limited by the power supply capabilities
  # When off, will use 5V from the USB port, which is enough to power the DAC and ESP32 with limited power
  - platform: gpio
    id: pd_enable
    pin: GPIO13
    restore_mode: ALWAYS_ON
    inverted: true
    name: "PD Power Enable"

  - platform: tas5805m
    # Will be operated automatially. When disabled DAC will drow dramatically less power
    enable_dac:
      name: Enable Louder
      id: enable_louder
      restore_mode: ALWAYS_ON
    # Will be operated automatially. If you use EQ it is required to set it ON
    enable_eq:
      name: Enable EQ Control
      restore_mode: RESTORE_DEFAULT_ON      

sensor:
  - platform: tas5805m
    faults_cleared:
      name: "Times Faults Cleared"

binary_sensor:
  - platform: tas5805m
    have_fault:
      name: Any Faults
      exclude: CLOCK_FAULT
    left_channel_dc_fault:
      name: Left Channel DC Fault
    right_channel_dc_fault:
      name: Right Channel DC Fault
    left_channel_over_current:
      name: Left Channel Over Current
    right_channel_over_current:
      name: Right Channel Over Current
    otp_crc_check:
      name: CRC Check Fault
    bq_write_failed:
      name: BQ Write Failure
    # I2S clock fault binary sensor is not really useful with speaker media player
    # since it generates clock faults when it manipulates I2S.
    # clock fault:
    #   name: I2S Clock Fault
    pcdd_over_voltage:
      name: PCDD Over Voltage
    pcdd_under_voltage:
      name: PCDD Under Voltage
    over_temp_shutdown:
      name: Over Temperature Shutdown Fault
    over_temp_warning:
      name: Over Temperature Warning
      id: over_temperature_warning
