defaults:
  task_stack_in_psram: "false"
  log_level: INFO
  enable_display: false
  enable_debug: false
  channel_mode: stereo

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: Esparagus Loud
  project:
    name: "sonocotta.esparagus_loud"
    version: "revE"
  min_version: 2026.2.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio

substitutions:
  pkg_display: !include
    file: "./esparagus-display.yml"
    vars:
      display_cs: GPIO5
      display_dc: GPIO04
      display_reset: GPIO32
      speaker_id: external_media_player

  pkg_debug: !include
    file: "./debug.yml"

packages:
  base: !include
    file: "./esparagus.yml"
    vars:
      led_gpio_pin: 33
  remote: !include
    file: "./esparagus-remote.yml"
    vars:
      gpio_pin: 39
      led_id: rgb_front_led
  display: ${ pkg_display if enable_display else {} }
  debug: ${ pkg_debug if enable_debug else {} }

captive_portal:

globals:
  - id: current_volume
    type: float
    initial_value: '0.2'
  - id: announcement_triggered
    type: bool
    initial_value: 'false'

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

speaker:
  - platform: i2s_audio
    id: i2s_speaker_id
    sample_rate: 48000
    i2s_dout_pin: GPIO22
    bits_per_sample: 16bit
    dac_type: external
    channel: ${channel_mode}
    timeout: never
    buffer_duration: 200ms
    mclk_multiple: 384
    use_apll: true

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: i2s_speaker_id
    num_channels: 2
    task_stack_in_psram: ${task_stack_in_psram}
    source_speakers:
      - id: announcement_mixer_input
        timeout: never
      - id: media_mixer_input
        timeout: never

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

media_player:
  - platform: sendspin
    id: sendspin_group_media_player

  - platform: speaker_source
    id: external_media_player
    volume_increment: 3%
    volume_initial: 50%
    name: "${friendly_name} Player"
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    announcement_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 1  # Stereo audio is unnecessary for announcements
      sample_rate: 48000
    media_pipeline:
      format: FLAC     # FLAC is the least processor intensive codec
      num_channels: 2
      sample_rate: 48000
    sources:
      - http_source
      - sendspin_source

    on_play:
      - if:
          condition:
            switch.is_off: enable_dac
          then:
            switch.turn_on: enable_dac

    on_idle:
      - if:
          condition:
            switch.is_on: enable_dac
          then:
            switch.turn_off: enable_dac

    on_announcement:
      - if:
          condition:
            switch.is_off: enable_dac
          then:
            switch.turn_on: enable_dac
      - if:
          condition:
            - lambda: return (!id(announcement_triggered));
          then:
            - lambda: |-
                id(announcement_triggered) = true;
                id(current_volume) = id(external_media_player).volume;
            - light.turn_on:
                id: rgb_front_led
                blue: 100%
                red: 0%
                green: 100%
                brightness: 50%
            - mixer_speaker.apply_ducking:
                  id: media_mixer_input
                  decibel_reduction: 40
                  duration: 0.0s
            - wait_until:
                media_player.is_announcing: external_media_player
            - delay: 0.75s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(announce_volume).state / 100.0;"
            - wait_until:
                - not:
                    media_player.is_announcing: external_media_player
            - mixer_speaker.apply_ducking:
                      id: media_mixer_input
                      decibel_reduction: 0
                      duration: 1.0s
            - media_player.volume_set:
                id: external_media_player
                volume: !lambda "return id(current_volume);"
            - light.turn_off:
                id: rgb_front_led
            - lambda: id(announcement_triggered) = false;

    on_state:
      if:
        condition:
          and:
            - lambda: return (!id(announcement_triggered));
            - not:
                media_player.is_announcing: external_media_player
        then:
          - mixer_speaker.apply_ducking:
              id: media_mixer_input
              decibel_reduction: 0
              duration: 1.0s

number:
  - platform: template
    name: Announce Volume
    id: announce_volume
    icon: mdi:volume-source
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50
    optimistic: true

switch:
  - platform: gpio
    icon: "mdi:speaker"
    name: Enable DAC
    id: enable_dac
    pin:
      number: GPIO13
    restore_mode: ALWAYS_OFF
